[package]
name = "bucket_proof"
type = "bin"
authors = [""]
compiler_version = ">=0.19.4"

[dependencies]
noir_trie_proofs = { git = "https://github.com/aragonzkresearch/noir-trie-proofs", tag = "main", directory = "lib" }
