/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CounterTest } from "./CounterTest";
export type { DSTest } from "./DSTest";
export type { Test } from "./Test";
